version: "3"

services:
  prod:
    build:
      context: .
      dockerfile: ja-fan/Dockerfile
    ports:
      - "5080:80"
      - "5443:443" 
    env_file:
      - .env
    networks:
      - "dotnet"
    depends_on:
      - "dotnet-db"
  
  dotnet-db:
    image: postgres:13
    ports:
      - "2345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - "dotnet"

volumes:
  postgres_data:
    
networks:
  dotnet:
    driver: bridge
