FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
EXPOSE 7226
EXPOSE 5226
WORKDIR /app

COPY . .
RUN dotnet restore "./ja-fan/ja-fan.csproj"
RUN dotnet dev-certs https --clean
RUN dotnet dev-certs https -t

ENTRYPOINT ["dotnet", "run", "--project", "./ja-fan/ja-fan.csproj"]
